version: "3.9"
services:
  client:
    build: .
    ports:
      - "9000:9000"
      - "6060:6060"
    volumes:
      - ~/client/logs:/client/logs
      - ~/client/data:/client/data
      - ~/client/configs:/client/configs

